# name: Prettier Formatter

# # This action works with pull requests and pushes
# on:
#   workflow_call:
#   pull_request:
#       branches: [master]

# jobs:
#   prettier:
#     runs-on: ubuntu-latest
#     # defaults:
#     #   run:
#     #     shell: bash
#     #     working-directory: react

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           # Make sure the actual branch is checked out when running on pull requests
#           ref: ${{ github.head_ref }}

#       - name: Main
#         run: ls

#       - name: Prettify code
#         uses: creyD/prettier_action@v4.2
#         with:
#           commit_message: "Code Indented!"
#           prettier_options: --write **/*.{js,css,html,json,ts,tsx,jsx} --config .prettierrc
